# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 3'

gem 'rspec'
gem 'rubocop', require: false
gem 'rubocop-performance', require: false
gem 'rubocop-rake', require: false
gem 'rubocop-rspec', require: false
